[General]

JustWorksRepairing = always
DeviceID = false

# Add dual adapter & A2DP auto-enable settings
Name = AA Proxy
Class = 0x200414
AutoEnable = true
ControllerMode = dual
DiscoverableTimeout = 0
PairableTimeout = 0

[Policy]
AutoEnable = true
